version: '3.8'
services:
  db:
    image: mysql:8.0.21
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Qw123456
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Qw123456
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  app-organization:
    image: app-organization:0.0.1
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - 8040:8080
    depends_on:
      - db
  app-party:
    image: app-party:0.0.1
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - 8041:8080
    depends_on:
      - db
  app-product:
    image: app-product:0.0.1
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - 8042:8080
    depends_on:
      - db
  app-user:
    image: app-user:0.0.1
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - 8043:8080
    depends_on:
      - db
volumes:
  db_data: