package com.client.domain

import java.util.UUID
import javax.persistence.*
import org.hibernate.annotations.LazyCollection
import org.hibernate.annotations.LazyCollectionOption

/**
* Identity of object in DifHub. Objects can be identify by globaly unique Id and localy unique name.
* @param id Id of the object. It is global unique identificator, optional for minor objects and required for major objects. When object created Id will be generated by backend service.
* @param name Name of the object. It is textual object identificator, need to be unique inside folder of the object.
* @param description Description for the object functionality. It is text with specification of object and way it used in application.
*/
@javax.annotation.Generated(value = ["org.openapitools.codegen.CodeCodegen"])

@Embeddable
data class Identity(

	@Column(name = "id", insertable = false, updatable = false)
	var id: String? = null,

	@Column(name = "name")
	var name: String? = null,

	@Column(name = "description")
	var description: String? = null

) 

